"use client";

/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element -- Shared Vinext and Netlify SPA client. */
import { useEffect, useMemo, useState } from "react";
import { createSeedStore, seedReviews } from "../../platform/seed";
import type { MenuProduct, Reservation, Review, StoreProfile, StoreRecord } from "../../platform/types";
import StorefrontClient from "../storefront/StorefrontClient";

type StudioView = "overview" | "site" | "menu" | "reservations" | "reviews" | "team" | "billing";
const money = (value: number) => `NT$ ${value.toLocaleString("zh-TW")}`;

export default function MerchantStudioClient({ initialSlug = "senri" }: { initialSlug?: string }) {
  const [store, setStore] = useState<StoreRecord>(() => createSeedStore());
  const [draftProfile, setDraftProfile] = useState<StoreProfile>(() => createSeedStore().draftProfile);
  const [draftProducts, setDraftProducts] = useState<MenuProduct[]>(() => createSeedStore().draftProducts);
  const [view, setView] = useState<StudioView>("overview");
  const [role, setRole] = useState<"owner" | "staff">("owner");
  const [preview, setPreview] = useState(false);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);
  const [reservations, setReservations] = useState<Reservation[]>([]);
  const [reviews, setReviews] = useState<Review[]>(seedReviews);
  const [staffName, setStaffName] = useState("");
  const [newProduct, setNewProduct] = useState({ name: "", price: 0, category: "人氣定食" });
  const slug = initialSlug || store.slug;

  useEffect(() => { const timer = window.setTimeout(async () => { try { const response = await fetch(`/api/stores?slug=${encodeURIComponent(slug)}`, { cache: "no-store" }); const result = await response.json() as { store?: StoreRecord }; if (result.store) { setStore(result.store); setDraftProfile(result.store.draftProfile); setDraftProducts(result.store.draftProducts); } } catch { setMessage("目前顯示示範資料；正式站 API 連線後會自動同步。"); } }, 0); return () => window.clearTimeout(timer); }, [slug]);
  useEffect(() => { Promise.all([fetch(`/api/reservations?storeId=${store.storeId}`).then((response) => response.ok ? response.json() : Promise.reject()), fetch(`/api/reviews?storeId=${store.storeId}`).then((response) => response.ok ? response.json() : Promise.reject())]).then(([reservationResult, reviewResult]) => { setReservations(reservationResult.reservations || []); setReviews(reviewResult.reviews || []); }).catch(() => undefined); }, [store.storeId]);

  const save = async (action: "save_draft" | "publish") => {
    setLoading(true); setMessage("");
    try {
      const response = await fetch("/api/stores", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug, action, profile: draftProfile, products: draftProducts }) });
      const result = await response.json() as { store?: StoreRecord; error?: string }; if (!response.ok || !result.store) throw new Error(result.error || "儲存失敗"); setStore(result.store); setDraftProfile(result.store.draftProfile); setDraftProducts(result.store.draftProducts); setMessage(action === "publish" ? "已發布，新版本已上線。" : "草稿已儲存，顧客目前看不到這些修改。");
    } catch (cause) { setMessage(cause instanceof Error ? cause.message : "儲存失敗"); } finally { setLoading(false); }
  };
  const restore = async (versionId: string) => { setLoading(true); try { const response = await fetch("/api/stores", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug, action: "restore", versionId }) }); const result = await response.json() as { store?: StoreRecord; error?: string }; if (!response.ok || !result.store) throw new Error(result.error || "還原失敗"); setStore(result.store); setDraftProfile(result.store.draftProfile); setDraftProducts(result.store.draftProducts); setMessage("舊版本已載入草稿，預覽後再發布即可上線。"); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "還原失敗"); } finally { setLoading(false); } };
  const addStaff = async () => { if (!staffName.trim()) return; const response = await fetch("/api/stores", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug, action: "add_staff", staffName }) }); const result = await response.json() as { store?: StoreRecord; error?: string }; if (result.store) { setStore(result.store); setStaffName(""); setMessage("員工帳號已建立（模擬邀請）。"); } else setMessage(result.error || "新增失敗"); };
  const updateReservation = async (reservation: Reservation, status: Reservation["status"]) => { const response = await fetch("/api/reservations", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ storeId: store.storeId, id: reservation.id, status }) }); if (response.ok) setReservations((current) => current.map((item) => item.id === reservation.id ? { ...item, status } : item)); };
  const replyReview = async (review: Review) => { const reply = window.prompt("輸入店家回覆", review.merchantReply); if (reply === null) return; const response = await fetch("/api/reviews", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ storeId: store.storeId, id: review.id, reply }) }); const result = await response.json() as { review?: Review }; if (result.review) setReviews((current) => current.map((item) => item.id === review.id ? result.review! : item)); };
  const addProduct = () => { if (!newProduct.name || newProduct.price <= 0) return; setDraftProducts((current) => [...current, { id: `custom-${crypto.randomUUID()}`, name: newProduct.name, description: "請補上餐點介紹", price: newProduct.price, category: newProduct.category, image: "/menu/rice-bowl.jpg", imageAlt: newProduct.name, optionGroups: [] }]); setNewProduct({ name: "", price: 0, category: "人氣定食" }); setMessage("餐點已加入草稿，發布後才會上線。"); };

  const dirty = useMemo(() => JSON.stringify(draftProfile) !== JSON.stringify(store.profile) || JSON.stringify(draftProducts) !== JSON.stringify(store.products), [draftProducts, draftProfile, store]);
  if (role === "staff") return <main className="staff-gate"><header><a className="brand" href="/"><span className="brand-mark">R</span><span>Rootable <b>森根</b></span></a><button onClick={() => setRole("owner")}>切換為店主示範</button></header><section><span className="store-avatar">{store.profile.logoText}</span><p className="merchant-kicker">員工模式</p><h1>{store.profile.name} 接單中心</h1><p>員工可以處理訂單、外帶與訂位，但看不到網站設定、付款與帳務。</p><div><a className="tenant-primary" href="/merchant/orders">開啟訂單工作台</a><button className="tenant-secondary" onClick={() => setView("reservations")}>查看訂位</button></div></section>{view === "reservations" && <section className="staff-reservations"><h2>今日訂位</h2>{reservations.length ? reservations.map((item) => <article key={item.id}><b>{item.time}・{item.customerName}</b><span>{item.partySize} 人・{item.phone}</span><button onClick={() => updateReservation(item, "seated")}>標記入座</button></article>) : <p>目前沒有新訂位。</p>}</section>}</main>;
  const nav: { id: StudioView; label: string; meta: string }[] = [{ id: "overview", label: "營運首頁", meta: "今日摘要" }, { id: "site", label: "店家網站", meta: dirty ? "有未發布修改" : "已同步" }, { id: "menu", label: "菜單管理", meta: `${draftProducts.length} 項` }, { id: "reservations", label: "訂位與外帶", meta: `${reservations.length} 筆` }, { id: "reviews", label: "顧客評論", meta: `${reviews.length} 則` }, { id: "team", label: "團隊權限", meta: `${store.staff.length} 人` }, { id: "billing", label: "付款與方案", meta: "免費版" }];
  return <main className="studio-page"><aside className="studio-sidebar"><a className="brand merchant-brand" href="/"><span className="brand-mark">R</span><span>Rootable <b>森根</b></span></a><div className="studio-store"><span>{store.profile.logoText}</span><div><b>{store.profile.name}</b><small>{store.slug}.rootable.tw</small></div></div><nav>{nav.map((item) => <button className={view === item.id ? "active" : ""} onClick={() => setView(item.id)} key={item.id}><span>{item.label}</span><small>{item.meta}</small></button>)}</nav><button className="staff-mode-button" onClick={() => setRole("staff")}>切換員工模式</button></aside><section className="studio-main"><header className="studio-topbar"><div><p className="merchant-kicker">店主後台</p><h1>{nav.find((item) => item.id === view)?.label}</h1></div><div><a href={`/s/${store.slug}`} target="_blank" rel="noreferrer">查看網站</a>{["site", "menu"].includes(view) && <><button onClick={() => setPreview(true)}>預覽草稿</button><button onClick={() => save("save_draft")} disabled={loading}>儲存草稿</button><button className="publish-button" onClick={() => save("publish")} disabled={loading || !dirty}>發布</button></>}</div></header>{message && <p className="studio-message" role="status">{message}</p>}
    {view === "overview" && <div className="studio-dashboard"><section className="studio-metrics"><article><span>今日訂單</span><b>24</b><small>較昨日 +12%</small></article><article><span>待處理</span><b>3</b><small>請前往工作台</small></article><article><span>今日營業額</span><b>{money(12840)}</b><small>含現金與模擬支付</small></article><article><span>本期代支付</span><b>{money(6820)}</b><small>預估實收 {money(6554)}</small></article></section><section className="studio-quick"><div><h2>開始營業</h2><p>接單工作台會即時收到內用與外帶訂單。</p><a className="tenant-primary" href="/merchant/orders">開啟平板接單</a></div><div><h2>分享你的店</h2><p>一般分享連結顯示店家首頁；桌牌連結會直接進入點餐。</p><code>rootable-tw.netlify.app/s/{store.slug}</code><code>/s/{store.slug}/order?table=A03</code></div></section><section className="studio-tasks"><h2>上線檢查</h2><label><input type="checkbox" defaultChecked/>店家資訊已完成</label><label><input type="checkbox" defaultChecked/>已有 {draftProducts.length} 項餐點</label><label><input type="checkbox"/>下載並列印桌牌 QR Code</label><label><input type="checkbox"/>申請 Rootable 代支付</label></section></div>}
    {view === "site" && <div className="studio-editor"><section><h2>品牌與首頁</h2><div className="editor-grid"><label>店家名稱<input value={draftProfile.name} onChange={(event) => setDraftProfile({ ...draftProfile, name: event.target.value })}/></label><label>一句話介紹<input value={draftProfile.tagline} onChange={(event) => setDraftProfile({ ...draftProfile, tagline: event.target.value })}/></label><label className="wide">品牌故事<textarea value={draftProfile.story} onChange={(event) => setDraftProfile({ ...draftProfile, story: event.target.value })}/></label><label className="wide">最新公告<textarea value={draftProfile.announcement} onChange={(event) => setDraftProfile({ ...draftProfile, announcement: event.target.value })}/></label><label>地址<input value={draftProfile.address} onChange={(event) => setDraftProfile({ ...draftProfile, address: event.target.value })}/></label><label>電話<input value={draftProfile.phone} onChange={(event) => setDraftProfile({ ...draftProfile, phone: event.target.value })}/></label><label>品牌主色<input type="color" value={draftProfile.theme.primary} onChange={(event) => setDraftProfile({ ...draftProfile, theme: { ...draftProfile.theme, primary: event.target.value } })}/></label><label>強調色<input type="color" value={draftProfile.theme.accent} onChange={(event) => setDraftProfile({ ...draftProfile, theme: { ...draftProfile.theme, accent: event.target.value } })}/></label></div></section><section><h2>發布紀錄</h2><p>每次發布都保留上一個版本；還原只會載入草稿，不會直接覆蓋線上內容。</p><div className="version-list">{store.versions.length ? store.versions.map((version, index) => <article key={version.id}><div><b>版本 {store.versions.length - index}</b><span>{new Date(version.createdAt).toLocaleString("zh-TW")}</span></div><button onClick={() => restore(version.id)}>載入草稿</button></article>) : <p>第一次發布後，版本會顯示在這裡。</p>}</div></section></div>}
    {view === "menu" && <div className="menu-editor"><section className="new-product-card"><h2>新增餐點</h2><input placeholder="餐點名稱" value={newProduct.name} onChange={(event) => setNewProduct({ ...newProduct, name: event.target.value })}/><input type="number" placeholder="價格" value={newProduct.price || ""} onChange={(event) => setNewProduct({ ...newProduct, price: Number(event.target.value) })}/><select value={newProduct.category} onChange={(event) => setNewProduct({ ...newProduct, category: event.target.value })}>{["人氣定食", "丼飯與麵", "飲品", "甜點"].map((item) => <option key={item}>{item}</option>)}</select><button onClick={addProduct}>加入草稿</button></section><section className="menu-editor-list">{draftProducts.map((product) => <article key={product.id}><img src={product.image} alt=""/><div><input value={product.name} onChange={(event) => setDraftProducts((current) => current.map((item) => item.id === product.id ? { ...item, name: event.target.value } : item))}/><span>{product.category}・{product.optionGroups.length} 組選項</span></div><label><input type="checkbox" checked={!product.soldOut} onChange={(event) => setDraftProducts((current) => current.map((item) => item.id === product.id ? { ...item, soldOut: !event.target.checked } : item))}/>供應中</label><input className="price-input" type="number" value={product.price} onChange={(event) => setDraftProducts((current) => current.map((item) => item.id === product.id ? { ...item, price: Number(event.target.value) } : item))}/><button aria-label={`刪除${product.name}`} onClick={() => setDraftProducts((current) => current.filter((item) => item.id !== product.id))}>刪除</button></article>)}</section></div>}
    {view === "reservations" && <section className="reservation-board"><header><div><h2>即將到店</h2><p>一般訂位免訂金；大桌與熱門時段依免費版統一規則收取。</p></div><b>{reservations.length} 筆</b></header>{reservations.length ? reservations.map((item) => <article key={item.id}><time>{item.date}<b>{item.time}</b></time><div><h3>{item.customerName}・{item.partySize} 人</h3><p>{item.phone}{item.note && `・${item.note}`}</p><span>{item.deposit ? `訂金 ${money(item.deposit)}・模擬已付` : "免訂金"}</span></div><strong>{item.status === "confirmed" ? "已確認" : item.status}</strong><div><button onClick={() => updateReservation(item, "seated")}>已入座</button><button onClick={() => updateReservation(item, "cancelled")}>取消</button></div></article>) : <div className="dashboard-empty"><b>目前沒有訂位</b><p>顧客從店家首頁預約後會出現在這裡。</p></div>}</section>}
    {view === "reviews" && <section className="review-board"><header><div><h2>已驗證評論</h2><p>只有完成訂單的顧客能評論。店家可回覆或檢舉，但不能刪除負評。</p></div><b>★ 4.5</b></header>{reviews.map((review) => <article key={review.id}><div><span>{"★".repeat(review.rating)}</span><b>{review.customerName}</b><small>訂單 {review.orderNo}</small></div><p>{review.comment}</p>{review.merchantReply && <blockquote>店家回覆：{review.merchantReply}</blockquote>}<footer><button onClick={() => replyReview(review)}>回覆</button><button onClick={() => fetch("/api/reviews", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ storeId: store.storeId, id: review.id, report: true }) }).then(() => setMessage("評論已送出檢舉，平台審核前仍會顯示。"))}>檢舉</button></footer></article>)}</section>}
    {view === "team" && <section className="team-board"><header><div><h2>團隊成員</h2><p>店主可管理網站與付款；員工只能處理訂單、外帶與訂位。</p></div><div><input placeholder="員工名稱" value={staffName} onChange={(event) => setStaffName(event.target.value)}/><button onClick={addStaff}>新增員工</button></div></header>{store.staff.map((member) => <article key={member.id}><span>{member.name.slice(0, 1)}</span><div><b>{member.name}</b><small>{member.role === "owner" ? "店主・完整權限" : "員工・營運權限"}</small></div><strong>{member.role === "owner" ? "店主" : "員工"}</strong></article>)}</section>}
    {view === "billing" && <section className="billing-board"><div className="plan-card"><p>目前方案</p><h2>免費版</h2><strong>NT$ 0<small>／月</small></strong><ul><li>店家網站與菜單</li><li>內用 QR 點餐與現金訂單</li><li>預約外帶與線上訂位</li><li>統一付款與訂金規則</li></ul></div><div className="pay-card"><p>Rootable 代支付</p><h2>有交易才付費</h2><strong>3.9%<small>／成功交易</small></strong><p>顧客不加價；每月彙整 LINE Pay、Apple Pay 與訂位訂金，再結算給店家。</p><button disabled>已開通模擬代支付</button></div><div className="pro-card"><h2>專業版解鎖</h2><p>自訂付款與訂金政策、自有網域、移除 Rootable 品牌、報表、更多員工、會員集點、優惠券與 LINE 通知。</p><button>登記專業版需求</button></div><p className="demo-notice">本頁所有 LINE、付款、退款、通知與撥款皆為試營運模擬。</p></section>}
  </section>{preview && <div className="studio-preview"><header><div><b>草稿預覽</b><span>尚未發布，顧客看不到</span></div><button onClick={() => setPreview(false)}>關閉預覽</button></header><div className="studio-preview-canvas"><StorefrontClient slug={store.slug} mode="website" previewStore={{ ...store, profile: draftProfile, products: draftProducts }}/></div><footer><span>這裡顯示尚未發布的店家資訊與菜單。</span><button className="publish-button" onClick={() => { setPreview(false); void save("publish"); }}>發布這個版本</button></footer></div>}</main>;
}
